// questions.js
// All question levels for the game.
// Level 1: SFW only
// Level 2: SFW + mild NSFW, non-chaotic
// Level 3: Dark / chaotic / unhinged, but not explicit
// Level 4: Maximum allowed chaos & NSFW-coded (non-explicit)

window.LEVEL_QUESTIONS = {
  1: [
    "Who’s the most likely to forget their own birthday?",
    "Who would survive the longest on a desert island?",
    "Who’s the worst person to trust with a secret?",
    "Who would accidentally join the wrong Zoom meeting?",
    "Who’s most likely to send an email without the attachment?",
    "Who’s most likely to lose their keys twice in the same day?",
    "Who has the best taste in food?",
    "Who would adopt the most pets?",
    "Who’s most likely to win a pub quiz?",
    "Who’s most likely to bail on plans but still complain they’re bored?",
    "Who would accidentally walk into the wrong toilet?",
    "Who would be late to their own wedding?",
    "Who’s most likely to forget everyone’s birthday but expect theirs celebrated?",
    "Who would thrive on a reality TV show?",
    "Who gives the worst advice but with the most confidence?",
    "Who’s the biggest overthinker?",
    "Who would accidentally wear pyjama bottoms to Tesco?",
    "Who would make friends with a stranger on a bus?",
    "Who’s most likely to spill their drink instantly?",
    "Who has the best fashion sense?",
    "Who’s the easiest to peer-pressure into plans?",
    "Who would be voted “class clown” in school?",
    "Who’s most likely to forget to reply for three days?",
    "Who’s secretly the most competitive?",
    "Who has the tidiest room?",
    "Who’s the messiest eater?",
    "Who’d cry at a film they’ve already seen?",
    "Who’s most likely to laugh in a serious situation?",
    "Who would do the best job in a zombie apocalypse?",
    "Who would befriend the zombie?",
    "Who’s most likely to lose their ID on a night out?",
    "Who’s the best storyteller?",
    "Who would sign up to too many societies at uni?",
    "Who would forget to cancel a subscription for a year?",
    "Who’s the loudest when excited?",
    "Who’s the quietest in group settings?",
    "Who would accidentally start a rumour?",
    "Who’s most likely to get into a random YouTube rabbit hole?",
    "Who has the nicest laugh?",
    "Who’s the most dramatic over nothing?",
    "Who’s the most laid-back?",
    "Who takes the longest to get ready?",
    "Who would pack way too much for a weekend away?",
    "Who’s most likely to ace a test without revising?",
    "Who’s most likely to fail because they revised?",
    "Who’s most likely to talk to themselves?",
    "Who’d be the best parent?",
    "Who’d be the most embarrassing parent?",
    "Who’s the biggest “I’ll do it tomorrow” person?",
    "Who’s most likely to become a teacher?",
    "Who’s the most wholesome?",
    "Who gives the best hugs?",
    "Who’s most likely to take a nap at a party?",
    "Who’s most likely to plan everything down to the minute?",
    "Who’d accidentally become famous on TikTok?",
    "Who’s most likely to buy something they absolutely don’t need?",
    "Who’s most likely to break their phone screen?",
    "Who’s most likely to forget where they parked?",
    "Who would become a millionaire out of sheer luck?",
    "Who’d get scammed online first?",
    "Who’s most likely to start a podcast?",
    "Who’d be the worst person to travel with?",
    "Who’d be the best person to travel with?",
    "Who’d get sunburnt instantly?",
    "Who’d complain the most on a hike?",
    "Who’s most likely to win “Bake Off”?",
    "Who’s most likely to lose their passport abroad?",
    "Who’s most likely to get lost in their own hometown?",
    "Who’d go viral for something wholesome?",
    "Who’d go viral for something embarrassing?",
    "Who talks the most?",
    "Who listens the best?",
    "Who’s most likely to procrastinate to dangerous levels?",
    "Who would start a business and forget about it?",
    "Who’s the most chaotic good?",
    "Who’s the most lawful neutral?",
    "Who’s most likely to forget to drink water all day?",
    "Who gives the best pep talks?",
    "Who would genuinely enjoy jury duty?",
    "Who’s most likely to cry at a dog advert?",
    "Who’s the most unexpectedly talented?",
    "Who’s most likely to audition for a game show?",
    "Who would win a karaoke contest?",
    "Who would refuse to do karaoke?",
    "Who’s most likely to talk their way out of trouble?",
    "Who’s most likely to talk their way into trouble?",
    "Who’d be the worst spy?",
    "Who’d be the best detective?",
    "Who’s most likely to accidentally steal something by forgetting they’re holding it?",
    "Who’s most likely to take the longest showers?",
    "Who’s most likely to get obsessed with a new hobby for a week?",
    "Who’s the most frugal?",
    "Who’s the biggest spender?",
    "Who would lose a debate instantly?",
    "Who would win a debate even if they’re wrong?",
    "Who’s most likely to overpack snacks?",
    "Who’s most likely to underpack snacks?",
    "Who’s most likely to forget anniversaries?",
    "Who’s the most organised?",
    "Who’s the least organised?",
    "Who’d get a dog first?",
    "Who’d get a cat first?",
    "Who’s most likely to send a message to the wrong chat?",
    "Who’s most likely to fail a vibe check?",
    "Who passes every vibe check?",
    "Who’s the most gullible?",
    "Who’s the most skeptical?",
    "Who’s most likely to mishear lyrics?",
    "Who’s most likely to quote films constantly?",
    "Who’s most likely to befriend the neighbour?",
    "Who’s most likely to forget to eat?",
    "Who’s most likely to forget they already ate?",
    "Who’s most likely to binge-watch a series in one sitting?",
    "Who’s most likely to leave dishes “to soak”?",
    "Who’s most likely to lose a debate to a child?",
    "Who’s most likely to correct your grammar?",
    "Who’s most likely to argue with Siri?",
    "Who’s most likely to name their plants?",
    "Who’s most likely to join a book club?",
    "Who’s most likely to break something new immediately?",
    "Who’s the best gift-giver?",
    "Who’s the worst gift-giver?",
    "Who’s most likely to talk during a movie?",
    "Who’s most likely to shush someone in a cinema?",
    "Who’s most likely to take embarrassing photos of everyone?",
    "Who’s most likely to overshare once comfortable?",
    "Who’s the most introverted?",
    "Who’s the most extroverted?",
    "Who’s most likely to have a strict skincare routine?",
    "Who’s most likely to lose a game instantly?",
    "Who’s most likely to take games way too seriously?",
    "Who’s most likely to apologise too much?",
    "Who’s most likely to never apologise?",
    "Who’s most likely to sleep through their alarm?",
    "Who’s most likely to wake up before everyone else?",
    "Who’s most likely to impulse-buy something ridiculous?",
    "Who’s most likely to return it the next day?",
    "Who’s the best at reading people?",
    "Who’s the worst at reading people?",
    "Who’d forget their own lunch but bring snacks for everyone else?",
    "Who’s most likely to use a planner religiously?",
    "Who’s most likely to wing everything?",
    "Who’s most likely to accidentally send a voice note?",
    "Who’s most likely to send a 3-minute voice note?",
    "Who’s the biggest people-pleaser?",
    "Who’s the most stubborn?",
    "Who’s most likely to enjoy a quiet night in?",
    "Who’s most likely to drag everyone out anyway?",
    "Who’s most likely to befriend their barista?",
    "Who’s most likely to be trending on TikTok for something dumb but harmless?"
  ],

  2: [
    "Who’s most likely to flirt without realising?",
    "Who’s most likely to get the ick the quickest?",
    "Who’s most likely to date someone purely because they’re fit?",
    "Who’s most likely to get back with their ex after saying they wouldn’t?",
    "Who falls in love after two dates?",
    "Who catches feelings for people who give them the bare minimum?",
    "Who’s most likely to get a crush on a coworker?",
    "Who’s most likely to date someone purely for the drama?",
    "Who gives the best relationship advice but never follows it?",
    "Who’s most likely to make things awkward on a first date?",
    "Who’s most likely to ghost someone for no reason?",
    "Who’s most likely to get ghosted?",
    "Who’s most likely to send mixed signals?",
    "Who’s most likely to receive mixed signals and overanalyse them?",
    "Who’s most likely to get caught stalking someone’s socials?",
    "Who’s most likely to accidentally like a photo from 5 years ago?",
    "Who’s most likely to message their ex when drunk?",
    "Who’s most likely to fall for a red flag?",
    "Who’s most likely to BE a red flag?",
    "Who’s most likely to start a situationship without meaning to?",
    "Who’s most likely to be in a situationship for too long?",
    "Who’s most likely to “fix” someone?",
    "Who’s most likely to need “fixing”?",
    "Who’s most likely to date someone who looks exactly like their ex?",
    "Who’s most likely to lie about their dating history?",
    "Who’s most likely to overshare on a first date?",
    "Who would bring up astrology on a date first?",
    "Who’s most likely to send a risky text then panic?",
    "Who’s most likely to flirt with someone they actually dislike?",
    "Who’s most likely to get friendzoned?",
    "Who’s most likely to friendzone someone?",
    "Who’s most likely to text “u up?”",
    "Who’s most likely to reply to “u up?”",
    "Who’s most likely to go on a date just for free food?",
    "Who’s most likely to embarrass themselves on a date?",
    "Who’s most likely to fall asleep during a film with their partner?",
    "Who’s most likely to send the cutest messages?",
    "Who’s most likely to send the driest messages?",
    "Who’s most likely to call someone pet names too soon?",
    "Who’s most likely to cook for a date?",
    "Who’s most likely to burn the meal for the date?",
    "Who’s most likely to get caught checking someone out?",
    "Who’s most likely to pretend they’re not jealous?",
    "Who’s most likely to be openly jealous?",
    "Who’s most likely to end up in a long-distance relationship?",
    "Who’s most likely to ruin a talking stage?",
    "Who’s most likely to fall for someone who’s emotionally unavailable?",
    "Who’s most likely to give someone TOO many chances?",
    "Who’s most likely to block someone and unblock them five minutes later?",
    "Who’s most likely to forget a date entirely?",
    "Who’s most likely to go on a date dressed like they didn’t care?",
    "Who’s most likely to go on a date overdressed?",
    "Who’s most likely to panic-delete their dating apps monthly?",
    "Who’s most likely to get matching outfits with their partner?",
    "Who’s most likely to use cute nicknames ironically until it becomes unironic?",
    "Who’s most likely to flirt to get what they want?",
    "Who’s most likely to flirt out of boredom?",
    "Who’s most likely to flirt with customer service?",
    "Who’s most likely to ruin their own crush by overthinking?",
    "Who’s most likely to like someone because “they smell nice”?",
    "Who’s most likely to fall for someone who gives them attention once?",
    "Who’s most likely to go on a second date even if the first one was terrible?",
    "Who’s most likely to bail halfway through a date?",
    "Who’s most likely to panic on a date and talk too much?",
    "Who’s most likely to panic and talk too little?",
    "Who’s most likely to laugh at the wrong moment on a date?",
    "Who’s most likely to get stood up and still apologise?",
    "Who’s most likely to cry after a breakup?",
    "Who’s most likely to not care after a breakup?",
    "Who’s most likely to buy something nice for their partner for no reason?",
    "Who’s most likely to forget their partner’s birthday?",
    "Who’s most likely to give the best kisses?",
    "Who’s most likely to make things awkward after a compliment?",
    "Who’s most likely to send a long message then delete it?",
    "Who’s most likely to stalk their crush’s Spotify playlists?",
    "Who’s most likely to fall for someone way too quickly?",
    "Who’s most likely to take way too long to fall for someone?",
    "Who’s most likely to post their partner everywhere?",
    "Who’s most likely to keep their relationship secret?",
    "Who’s most likely to screenshot conversations to send to the group chat?",
    "Who’s most likely to get the group to help write their texts?",
    "Who’s most likely to misinterpret flirting entirely?",
    "Who’s most likely to flirt without meaning it?",
    "Who’s most likely to date someone who’s bad for them because they’re bored?",
    "Who’s most likely to be the hopeless romantic?",
    "Who’s most likely to be the emotionally unavailable one?",
    "Who’s most likely to get the most dating app matches?",
    "Who’s most likely to brag about their matches?",
    "Who’s most likely to use the worst pickup lines?",
    "Who’s most likely to use surprisingly good pickup lines?",
    "Who’s most likely to date someone younger?",
    "Who’s most likely to date someone older?",
    "Who’s most likely to flirt with someone's sibling?",
    "Who’s most likely to have a secret crush in the room?",
    "Who’s most likely to start drama accidentally?",
    "Who’s most likely to keep things casual forever?",
    "Who’s most likely to get too attached?",
    "Who’s most likely to panic if someone gets attached to them?",
    "Who’s most likely to fall for someone they’ve never met?",
    "Who’s most likely to get a crush on someone from a TV show?",
    "Who’s most likely to flirt over text but be shy in person?",
    "Who’s most likely to flirt better in person than over text?",
    "Who’s most likely to overshare personal details while flirting?",
    "Who’s most likely to tell someone they like them on the wrong day?",
    "Who’s most likely to “accidentally” send a selfie?",
    "Who’s most likely to get caught reading old messages?",
    "Who’s most likely to go on a date with someone purely for the vibes?",
    "Who’s most likely to date someone their friends don’t like?",
    "Who’s most likely to date someone their friends LOVE?",
    "Who’s most likely to stay talking to someone even when they know it’s doomed?",
    "Who’s most likely to flirt with someone at the wrong time?",
    "Who’s most likely to date someone messy?",
    "Who’s most likely to date someone annoyingly perfect?",
    "Who’s most likely to have a friends-to-lovers moment?",
    "Who’s most likely to have an enemies-to-lovers moment?",
    "Who’s most likely to take the longest getting ready for a date?",
    "Who’s most likely to bail on a date last minute?",
    "Who’s most likely to agree to a date they don’t want to go on?",
    "Who’s most likely to talk about their ex on a date?",
    "Who’s most likely to bring up marriage too early?",
    "Who’s most likely to panic if someone brings up marriage to them?",
    "Who’s most likely to make a playlist for their crush?",
    "Who’s most likely to receive a playlist?",
    "Who’s most likely to flirt with someone’s parents by accident?",
    "Who’s most likely to develop a crush on someone unavailable?",
    "Who’s most likely to reject someone too harshly?",
    "Who’s most likely to reject someone too softly?",
    "Who’s most likely to message someone when lonely then ignore them later?",
    "Who’s most likely to get back with someone after one message?",
    "Who’s most likely to pretend they don’t care when they do?",
    "Who’s most likely to overshare trauma too early?",
    "Who’s most likely to be too mysterious for their own good?",
    "Who’s most likely to get caught flirting on a night out?",
    "Who’s most likely to flirt with someone’s friend?",
    "Who’s most likely to fall for someone with terrible chat?",
    "Who’s most likely to fall for someone with elite chat but nothing else?",
    "Who’s most likely to have a massive crush and tell no one?",
    "Who’s most likely to have a massive crush and tell everyone?",
    "Who’s most likely to get the most compliments?",
    "Who’s most likely to give the most compliments?",
    "Who’s most likely to get “the ick” over something tiny?",
    "Who’s most likely to give someone else the ick?",
    "Who’s most likely to date someone just because they’re funny?",
    "Who’s most likely to date someone just because they’re fit?",
    "Who’s most likely to be the clingiest?",
    "Who’s most likely to be the chillest partner?",
    "Who’s most likely to accidentally lead someone on?",
    "Who’s most likely to accidentally break someone’s heart?",
    "Who’s most likely to become someone’s rebound?",
    "Who’s most likely to choose a talking stage over sleep?"
  ],

  3: [
    "Who’s most likely to ruin their own life for someone they barely know?",
    "Who’s most likely to go back to someone who’s objectively terrible for them?",
    "Who gives the strongest “villain arc pending” energy?",
    "Who’s most likely to manipulate a situation and pretend they didn’t?",
    "Who’s most likely to lie even when the truth would’ve been easier?",
    "Who’s most likely to fall for someone purely because they treat them badly?",
    "Who’s most likely to be the reason a friend group breaks up?",
    "Who’s the biggest walking red flag?",
    "Who’s most likely to emotionally destroy someone then say “lol sorry”?",
    "Who gives off “main character but in a toxic way” vibes?",
    "Who’s most likely to become obsessed with someone after one conversation?",
    "Who’s most likely to make someone obsessed with them?",
    "Who’s most likely to ruin a talking stage for sport?",
    "Who would pick chaos over peace every single time?",
    "Who’s most likely to get into a messy entanglement they can’t escape?",
    "Who’d argue with someone and not remember what the argument was about?",
    "Who’s most likely to betray someone accidentally then blame them?",
    "Who’s most likely to betray someone deliberately and still sleep fine?",
    "Who’s most likely to disappear for 3 months then return like nothing happened?",
    "Who’s most likely to emotionally attach to the worst possible person?",
    "Who’s most likely to get caught doing something questionable in public?",
    "Who’s the most unhinged when drunk?",
    "Who would definitely get banned from a bar at some point in life?",
    "Who gives “argues with strangers for fun” vibes?",
    "Who’s most likely to cause chaos in a group project and vanish?",
    "Who’s most likely to take a joke way too far?",
    "Who’s most likely to pull a petty stunt and deny it?",
    "Who’s most likely to spin a story so well everyone believes the lie?",
    "Who’s most likely to ruin someone’s night without noticing?",
    "Who’s most likely to ruin someone’s night on purpose?",
    "Whose apology would you never trust?",
    "Who’s most likely to sabotage a relationship because they got bored?",
    "Who’s most likely to be the problem in their relationships?",
    "Who’s most likely to date someone purely to distract themselves?",
    "Who’s most likely to pretend they’re fine while absolutely not fine?",
    "Who’s most likely to create drama out of thin air?",
    "Who gives the strongest “toxic but irresistible” vibe?",
    "Who’s most likely to ignore someone for weeks then message “wyd”?",
    "Who’s most likely to leave someone on read out of spite?",
    "Who’s most likely to manipulate someone with compliments?",
    "Who’s most likely to manipulate someone with silence?",
    "Who’s most likely to “breadcrumb” someone on purpose?",
    "Who treats talking stages like job applications?",
    "Who secretly loves arguments?",
    "Who’s most likely to flirt with someone unavailable?",
    "Who’s most likely to be unavailable but act offended when someone moves on?",
    "Who’s most likely to be emotionally confusing on purpose?",
    "Who has the biggest delulu energy?",
    "Who’s most likely to date for convenience instead of feelings?",
    "Who’s most likely to juggle too many people at once?",
    "Who’s most likely to end up in a messy love triangle?",
    "Who’s most likely to create a messy love triangle?",
    "Who’s most likely to start drama in the group chat then mute it?",
    "Who’s the biggest “it wasn’t that deep” liar?",
    "Who’s most likely to ruin a friendship over something trivial?",
    "Who’s most likely to misinterpret something on purpose just to argue?",
    "Who gives the strongest “chaotic neutral” vibes?",
    "Who’s most likely to embarrass themselves loudly and publicly?",
    "Who’s most likely to embarrass someone else loudly and publicly?",
    "Who’s most likely to disappear after saying “be right back”?",
    "Who’s most likely to argue with staff at a bar or restaurant?",
    "Who would 100% get into beef with a stranger on a night out?",
    "Who’s most likely to be dramatic for the plot?",
    "Who sees red flags as challenges?",
    "Who is the red flag challenge?",
    "Who’s most likely to talk smack then forget they said it?",
    "Who’s most likely to cause tension the moment they walk in?",
    "Who’s most likely to love-bomb someone into confusion?",
    "Who’s most likely to “ghost then haunt”?",
    "Who’s most likely to block someone mid-sentence?",
    "Who would start a rumour just to see what happens?",
    "Who’s most likely to cause long-term beef within the friend group?",
    "Who’s most likely to emotionally ruin someone by accident?",
    "Who’s most likely to emotionally ruin someone on purpose?",
    "Who’s the most likely to have a secret rival?",
    "Who’s most likely to compare themselves to everyone constantly?",
    "Who’s most likely to stalk someone online to an unhealthy level?",
    "Who’s most likely to catch someone stalking them online?",
    "Who’s most likely to get way too invested in someone else’s drama?",
    "Who’s most likely to create drama if none exists?",
    "Who’s most likely to cry during an argument to win?",
    "Who’s most likely to go silent during an argument to win?",
    "Who’s most likely to bring up unrelated drama mid-argument?",
    "Who’s most likely to keep receipts for years?",
    "Who’s least trustworthy when the group splits into teams?",
    "Who’s most likely to stir the pot just to sit back and watch?",
    "Who’s most likely to use someone for attention?",
    "Who’s most likely to be used for attention?",
    "Who’s most likely to pretend they don’t care until it’s too late?",
    "Who’s most likely to ruin their own life for the plot twist?",
    "Who’s most likely to date the same “type” forever despite failure?",
    "Who’s most likely to become obsessed with someone toxic?",
    "Who’s most likely to be someone's toxic obsession?",
    "Who’s most likely to lie for sympathy?",
    "Who’s most likely to lie to avoid responsibility?",
    "Who’s most likely to emotionally shut down during chaos?",
    "Who’s most likely to thrive during chaos?",
    "Who’s most likely to escalate a small issue into a major crisis?",
    "Who’s most likely to downplay a major crisis like it’s nothing?",
    "Who’s most likely to ruin a date with overconfidence?",
    "Who’s most likely to ruin a date with self-sabotage?",
    "Who’s most likely to make someone cry unintentionally?",
    "Who’s most likely to make someone cry intentionally?",
    "Who’s most likely to get exposed in a group chat?",
    "Who’s most likely to expose someone else in a group chat?",
    "Who’s most likely to forgive someone who shouldn’t be forgiven?",
    "Who’s most likely to hold a grudge for eternity?",
    "Who’s most likely to lash out when jealous?",
    "Who’s most likely to deny jealousy while clearly jealous?",
    "Who’s most likely to emotionally manipulate without realising?",
    "Who’s most likely to emotionally manipulate very intentionally?",
    "Who’s most likely to start a fight and play the victim?",
    "Who’s most likely to ruin their own happiness out of fear?",
    "Who’s most likely to waste potential out of laziness?",
    "Who’s most likely to push people away before they get close?",
    "Who’s most likely to overshare deep trauma at the wrong moment?",
    "Who’s most likely to trauma-bond with the wrong person?",
    "Who’s most likely to start a cult accidentally?",
    "Who’s most likely to join a cult accidentally?",
    "Who’s most likely to join a cult on purpose just for the story?",
    "Who’s most likely to have a borderline evil alter ego?",
    "Who’s most likely to surround themselves with toxic people?",
    "Who’s most likely to be the toxic person in the group?",
    "Who’s most likely to date someone purely for chaos energy?",
    "Who’s most likely to flirt with their friend’s enemy?",
    "Who’s most likely to get caught lying about something tiny?",
    "Who’s most likely to brag about something embarrassing?",
    "Who’s most likely to make an unhinged decision at 3AM?",
    "Who’s most likely to wake up with instant regret?",
    "Who’s most likely to get so defensive they incriminate themselves?",
    "Who’s most likely to guilt-trip without trying?",
    "Who’s most likely to guilt-trip with intention?",
    "Who’s most likely to tell someone what they want to hear, not the truth?",
    "Who’s most likely to blow up someone else’s relationship accidentally?",
    "Who’s most likely to blow up someone else’s relationship intentionally?",
    "Who’s the biggest backhanded compliment giver?",
    "Who’s the biggest backhanded compliment receiver?",
    "Who’s most likely to pretend they’re over someone when they’re not?",
    "Who’s most likely to use someone as a rebound?",
    "Who’s most likely to be someone’s rebound and not notice?",
    "Who’s most likely to get caught in a scandal?",
    "Who’s most likely to create a scandal out of boredom?",
    "Who’s most likely to ruin someone’s trust then act confused?",
    "Who’s most likely to get exposed on social media?",
    "Who’s most likely to become the villain in someone else’s story?",
    "Who’s most likely to destroy their reputation with one decision?",
    "Who’s most likely to never learn from mistakes?",
    "Who’s most likely to always learn too late?",
    "Who’s most likely to apologise only when caught?",
    "Who’s most likely to pretend they’ve “changed” when they absolutely haven’t?"
  ],

  4: [
    "Who’s most likely to ruin someone’s life because they were bored and horny?",
    "Whose search history would end the group chat instantly?",
    "Who’s most likely to accidentally send a risky photo to the wrong person and then blame their phone?",
    "Who looks innocent but absolutely is not?",
    "Who’s most likely to sleep with someone just to win a bet?",
    "Who’s most likely to go home with someone they swore they hated?",
    "Who’s most likely to flirt their way out of serious consequences?",
    "Who flirts like it’s a survival strategy?",
    "Who’s most likely to have a “secret roster” no one knows about?",
    "Who’s most likely to hook up with someone specifically for validation?",
    "Who’d definitely panic if someone asked “so what are we?”",
    "Who’s most likely to ruin a talking stage because they found someone hotter?",
    "Who’s the biggest walking ick but somehow still irresistible?",
    "Who’s most likely to get exposed for being two-faced in DMs?",
    "Who’s most likely to overshare spicy details way too soon?",
    "Who’s most likely to lie about why they’re staying over at someone’s house?",
    "Who gives off the strongest “I’ve done questionable things and I’d do them again” energy?",
    "Who’s most likely to fall for someone purely because the chaos was attractive?",
    "Who’s most likely to sleep somewhere questionable after a night out?",
    "Who’s most likely to have a type they would never admit out loud?",
    "Who would catch feelings for someone wildly inappropriate?",
    "Who’s most likely to flirt with someone’s sibling out of spite?",
    "Who’s most likely to talk a big game but fold instantly?",
    "Who’s most likely to use someone as a rebound and make it their personality?",
    "Who’s most likely to date someone only because they’re “a bit toxic, but fit”?",
    "Who’s most likely to gaslight someone so well they don’t even realise?",
    "Who’s most likely to play both sides of an argument for entertainment?",
    "Who’s most likely to get attached to someone who openly doesn’t like them?",
    "Who’s the most emotionally dangerous when ignored?",
    "Who’s most likely to start a fight then act clueless?",
    "Who’s most likely to trauma-bond someone into obsession?",
    "Who’s most likely to pretend they’re the victim even when they caused everything?",
    "Who’s most likely to intentionally confuse someone just to keep them interested?",
    "Who’s most likely to fall for someone specifically because they’re toxic?",
    "Who’s most likely to mirror someone to manipulate them?",
    "Who’s most likely to emotionally disappear without warning?",
    "Who would thrive as a morally questionable therapist?",
    "Who’s most likely to accidentally lead two people on at once?",
    "Who’s most likely to be the reason someone needs therapy?",
    "Who’s most likely to pretend they’ve changed just to keep someone around?",
    "Who’s most likely to project their issues onto others flawlessly?",
    "Who’s most likely to sabotage themselves and blame the universe?",
    "Who’s most likely to form a connection then ruin it immediately?",
    "Who’s most likely to use silence as a weapon?",
    "Who’s most likely to get jealous of someone they don’t even want?",
    "Who’s most likely to romanticise someone who’s objectively awful?",
    "Who’s most likely to catch feelings purely because someone rejected them?",
    "Who’s most likely to flirt with someone just to test their power?",
    "Who’s most likely to emotionally drain someone without noticing?",
    "Who’s most likely to emotionally drain someone on purpose?",
    "Who’s most likely to wake up in a stranger’s living room with no explanation?",
    "Who’s most likely to lose their dignity before their wallet on a night out?",
    "Who’s most likely to get banned from a club but wear it like a badge of honour?",
    "Who’s most likely to flirt with security just to get back in?",
    "Who’s most likely to disappear for 2 hours then return with chaos in their eyes?",
    "Who’s most likely to start chanting something stupid in the smoking area?",
    "Who’s most likely to get kicked out for “just vibing too aggressively”?",
    "Who’s most likely to argue with a taxi driver for sport?",
    "Who’s most likely to end up in an Uber going the wrong direction and stay quiet?",
    "Who’s most likely to promise “I’m behaving tonight” then immediately not behave?",
    "Who’s most likely to fall in love with someone they met in the queue for a kebab?",
    "Who’s most likely to get on a random bus drunk and call it an adventure?",
    "Who’s most likely to have the night of their life and not remember any of it?",
    "Who’s most likely to befriend the bartenders by force?",
    "Who’s most likely to start a singalong in the club unprovoked?",
    "Who’s most likely to hype up someone they don’t know in the toilets?",
    "Who’s most likely to embarrass the group but also make the night iconic?",
    "Who’s most likely to get emotional in the smoking area about something stupid?",
    "Who’s most likely to wake up with a traffic cone in their room?",
    "Who’s most likely to flirt with someone purely for free drinks?",
    "Who’s most likely to leave with the wrong friend group?",
    "Who’s most likely to get banned from Wetherspoons for life?",
    "Who’s most likely to start a chant in the Uber home?",
    "Who’s most likely to end up dancing alone like they’re the main character?",
    "Who’s most likely to lose something important and not care until the next morning?",
    "Who looks like they’ve ruined multiple people’s lives without meaning to?",
    "Who looks like they’ve ruined lives very intentionally?",
    "Who’s most likely to go feral when their ego gets poked?",
    "Who would survive solely on delusion and iced coffee?",
    "Who acts confident but is one insult away from collapse?",
    "Who’s most likely to get humbled publicly?",
    "Who’s most likely to humble someone publicly?",
    "Who’s the biggest “I can fix them” idiot?",
    "Who’s the biggest “I want to be fixed” idiot?",
    "Who screams red flag energy on sight?",
    "Who’s most likely to accidentally reveal a secret because they forgot it was a secret?",
    "Who’s most likely to trip over their own lies?",
    "Who’s most likely to overshare and then blame the alcohol?",
    "Who’s most likely to become someone’s worst mistake?",
    "Who’s most likely to be someone’s worst mistake and proud of it?",
    "Who’s got the strongest “no thoughts, just vibes” aesthetic?",
    "Who’s got the strongest “too many thoughts, bad vibes” aesthetic?",
    "Who’s most likely to look innocent but be absolute chaos?",
    "Who’s most likely to look chaotic but be secretly responsible?",
    "Who’s most likely to have a villainous laugh?",
    "Who’s most likely to cause long-term emotional damage with a single sentence?",
    "Who’s most likely to roast someone so hard they reconsider their identity?",
    "Who’s most likely to cry from laughing at their own roast?",
    "Who’s most likely to argue with a mirror?",
    "Whose resting face screams “don’t talk to me”?",
    "Who’s most likely to end up in someone’s bed without remembering how?",
    "Who’s most likely to flirt with someone’s partner just to see what happens?",
    "Who’s most likely to get a DM that changes their entire personality?",
    "Who’s most likely to have a secret “situationship graveyard”?",
    "Who’s most likely to willingly ignore every red flag because the person is fit?",
    "Who’s most likely to catch feelings purely because someone is toxic?",
    "Who’s most likely to flirt then act shocked someone flirted back?",
    "Who’s most likely to send a risky message and instantly regret it?",
    "Who’s most likely to wake up to messages they don’t remember sending?",
    "Who treats every talking stage like a competition?",
    "Who’s most likely to crush someone’s confidence for fun?",
    "Who’s most likely to twist a story so well the group believes them instantly?",
    "Who’s most likely to pretend they’ve moved on while absolutely not moved on?",
    "Who’s most likely to emotionally breadcrumb someone into madness?",
    "Who’s most likely to hold a grudge until the heat death of the universe?",
    "Who’s most likely to study someone’s behaviour like a case file?",
    "Who’s most likely to hurt someone’s feelings with brutal honesty?",
    "Who’s most likely to purposely flirt with someone to make someone else jealous?",
    "Who’s most likely to love-bomb then vanish?",
    "Who’s most likely to vanish then come back love-bombing?",
    "Who’s most likely to lose all their belongings but gain three new friends?",
    "Who’s most likely to end up dancing on a table?",
    "Who’s most likely to get emotional about chips?",
    "Who’s most likely to befriend the DJ?",
    "Who’s most likely to fall over nothing and blame the floor?",
    "Who’s most likely to scream-sing in the toilets?",
    "Who’s most likely to start drama then go to the bar like nothing happened?",
    "Who’s most likely to get kicked out of the club and be happy about it?",
    "Who’s most likely to flirt with two people at once and get away with it?",
    "Who’s most likely to flirt with two people at once and not get away with it?",
    "Who’s most likely to lie about their weekend because the truth is unhinged?",
    "Who’s most likely to emotionally break someone then ask why they’re upset?",
    "Who’s most likely to ruin their own reputation in one night?",
    "Who’s most likely to ruin someone else’s reputation in one sentence?",
    "Who’s most likely to become the reason someone moves cities?",
    "Who’s most likely to flirt with danger emotionally or socially?",
    "Who’s most likely to hide a messy past behind a wholesome exterior?",
    "Who’s most likely to collect enemies accidentally?",
    "Who’s most likely to collect enemies intentionally?",
    "Who’s most likely to overshare something too dark and laugh?",
    "Who’s most likely to use banter as a weapon?",
    "Who’s most likely to pretend they’re over someone for the aesthetic?",
    "Who’s most likely to manipulate the group dynamic for fun?",
    "Who’s most likely to be the reason someone doubts themselves?",
    "Who’s most likely to have a chaotic era yearly?",
    "Who’s most likely to spread unhinged energy wherever they go?",
    "Who’s most likely to thrive in toxic situations?",
    "Who’s most likely to commit to the bit even when the bit is harmful?",
    "Who’s most likely to ruin the night and still be the funniest one there?",
    "Who’s most likely to look back at their life and genuinely wonder, “How am I still alive?”"
  ]
};

// Optional: choose a default if some parts of your code still expect BASE_QUESTIONS
// For example, default to level 2 or 3:
window.BASE_QUESTIONS = window.LEVEL_QUESTIONS[2];
